
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ===== PostgreSQL - DEV =====

spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=product_user
spring.datasource.password=ProductServer@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
