management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true


management.endpoint.env.enabled=false
management.endpoint.beans.enabled=false
management.endpoint.conditions.enabled=false
management.endpoint.configprops.enabled=false
management.endpoint.mappings.enabled=false
management.endpoint.threaddump.enabled=false
management.endpoint.heapdump.enabled=false
management.endpoint.shutdown.enabled=false
management.endpoint.logfile.enabled=false
management.endpoint.loggers.enabled=false
management.endpoint.scheduledtasks.enabled=false
management.endpoint.sessions.enabled=false
management.endpoint.quartz.enabled=false
